# Generated by Django 5.1 on 2024-08-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='ach2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ach3',
        ),
    ]
